spring:
  datasource:
    url: jdbc:mysql://120.26.61.213:3306/dataease?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: P=4vVT2D!nD)G?z3
  messages:
    basename: i18n/lic,i18n/core,i18n/permissions,i18n/xpack
  flyway:
    enabled: true
    table: de_standalone_version
    validate-on-migrate: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml


